version: "2"
linters:
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - errname
    - errorlint
    - exhaustive
    - goconst
    - goprintffuncname
    - gosec
    - ireturn
    - makezero
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - unconvert
    - usetesting
    - wastedassign
  settings:
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
        - Sqlmock
        - LogRecord
        - Index
        - Predicate
        - Expression
        - Constant
        - Term
        - Statement$
        - Scan
        - Plan
    predeclared:
      ignore:
        - max
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
