linters:
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gofumpt
    - mnd
    - goprintffuncname
    - gosec
    # - ifshort
    - ireturn
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    # - nolintlint
    # - nonamedreturns
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tenv
    - testpackage
    - unconvert
    - wastedassign
    # - wsl

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  ireturn:
    # ireturn allows using `allow` and `reject` settings at the same time.
    # Both settings are lists of the keywords and regular expressions matched to interface or package names.
    # keywords:
    # - `empty` for `interface{}`
    # - `error` for errors
    # - `stdlib` for standard library
    # - `anon` for anonymous interfaces

    # By default, it allows using errors, empty interfaces, anonymous interfaces,
    # and interfaces provided by the standard library.
    allow:
      - anon
      - error
      - empty
      - stdlib
      # You can specify idiomatic endings for interface
      - (or|er)$
      - Sqlmock
      - LogRecord
      - Index
      - Predicate
      - Expression
      - Constant
      - Term
      - Statement$
      - Scan
      - Plan
